---
- hosts: bastion
  become: true
  # vars:
  #   bastionIp: "{{ bastionIp }}" 
  #   elasticsearchIp: "{{ elasticsearchIp }}"
  roles:
    - nginx

- hosts: elasticsearch
  become: true
  roles:
    - elasticsearch_kibana
