---
- hosts: bastion
  become: true
  vars:
    bastionIp: "{{ lookup('file', '/var/lib/jenkins/workspace/project_es/terraform_es/bastion_ip.txt') }}"
    elasticsearchIp: "{{ lookup('file', '/var/lib/jenkins/workspace/project_es/terraform_es/elasticsearch_ip.txt') }}"
  roles:
    - nginx

- hosts: elasticsearch
  become: true
  vars:
    elasticsearchIp: "{{ lookup('file', '/var/lib/jenkins/workspace/project_es/terraform_es/elasticsearch_ip.txt') }}"
  roles:
    - elasticsearch_kibana
