---
- hosts: bastion
  become: true
  vars:
    bastionIp: "{{ lookup('file', 'bastion_ip.txt') }}"
    elasticsearchIp: "{{ lookup('file', 'elasticsearch_ip.txt') }}"
  roles:
    - nginx

- hosts: elasticsearch
  become: true
  roles:
    - elasticsearch_kibana
