---

- name: Ensure wget is installed
  apt:
    name: wget
    state: present
    update_cache: yes

- name: Add Elasticsearch GPG key
  command: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    _uses_shell: true

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add Elasticsearch APT repository for version 8.15
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: elastic-8.x

- name: Update apt cache and install Elasticsearch 8.15
  apt:
    name: elasticsearch=8.15.0
    state: present
    update_cache: yes
  notify:
    - restart elasticsearch

- name: Install Kibana 8.15 and Logstash
  apt:
    name:
      - kibana=8.15.0
      - logstash
    state: present
    update_cache: yes
  notify:
    - restart kibana

- name: Template kibana.yml
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: '0644'
  notify:
    - restart kibana

- name: Template elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: '0644'
  notify:
    - restart elasticsearch

- name: Start Elasticsearch service
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

- name: Start Kibana service
  systemd:
    name: kibana
    state: started
    enabled: yes

- name: Check the status of Kibana and Elasticsearch
  command: systemctl status {{ item }}
  with_items:
    - kibana
    - elasticsearch
  register: service_status
  ignore_errors: yes

- name: Display status of Kibana and Elasticsearch services
  debug:
    msg: "{{ service_status.results | map(attribute='stdout_lines') | list }}"


